# Dependabot configuration
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore minor updates for stability
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]