# =============================================================================
# Summit Hip Numbers Media Player Configuration - DISTRIBUTION VERSION
# =============================================================================
#
# This configuration file is for the portable Windows distribution.
# All paths are relative to the executable location for portability.
#
# Directory structure for distribution:
# summit_hip_numbers/
# ├── summit_hip_numbers.exe
# ├── config.toml (this file)
# ├── videos/
# │   ├── 001_video.mp4
# │   ├── 002_video.mp4
# │   └── ...
# ├── splash/
# │   ├── splash1.png
# │   └── ...
# └── logo/
#     └── logo.svg
#
# =============================================================================

# =============================================================================
# VIDEO SETTINGS
# =============================================================================
[video]
# Directory containing video files to be played
# For distribution, videos are in the 'videos' folder next to the executable
directory = "./videos"

# =============================================================================
# SPLASH SCREEN SETTINGS
# =============================================================================
[splash]
# Enable/disable the splash screen on application startup
enabled = true

# Duration in seconds to display the splash screen
duration_seconds = 3.0

# Text to display on splash screen when no images are available
text = "SUMMIT PROFESSIONAL Solutions\nMedia Player"

# Background color of the splash screen (hex format)
background_color = "#000000"

# Text color for splash screen text (hex format)
text_color = "#FFFFFF"

# Show splash screen every N videos
# 0 = Only show at application startup
# 1 = Show before every video
# 2 = Show before every 2nd video
# 3 = Show before every 3rd video
# etc.
interval = 0

# Splash screen rotation mode:
# - "cycle": Cycle through splash screens in order (default)
# - "random": Pick a random splash screen each time
# - "static": Always show the same splash screen (requires static_splash_path)
# rotation_mode = "cycle"

# When using rotation_mode = "static", specify the path to the splash image
# static_splash_path = "./splash/specific_splash.png"

# Directory containing splash screen images (PNG, JPG, JPEG, BMP)
# For distribution, splash images are in the 'splash' folder next to the executable
directory = "./splash"

# =============================================================================
# LOGGING SETTINGS
# =============================================================================
[logging]
# Name of the log file (created in the same directory as the executable)
file = "summit_hip_numbers.log"

# Maximum number of lines to keep in the log file
max_lines = 10000

# =============================================================================
# DEMO MODE SETTINGS
# =============================================================================
[demo]
# Timeout in seconds before the demo version automatically exits
timeout_seconds = 300

# Maximum number of videos to load in demo mode
max_videos = 5

# Maximum hip number allowed in demo mode
hip_number_limit = 5

# =============================================================================
# USER INTERFACE SETTINGS
# =============================================================================
[ui]
# -----------------------------------------------------------------------------
# WINDOW & DISPLAY SETTINGS
# -----------------------------------------------------------------------------
# Application window dimensions in pixels
window_width = 1920
window_height = 1080

# Layout proportions as decimal values (0.0 to 1.0)
video_height_ratio = 0.92  # 92% of screen height for video display
bar_height_ratio = 0.08    # 8% of screen height for status bar

# Enable fullscreen kiosk mode (removes window decorations and borders)
kiosk_mode = true

# -----------------------------------------------------------------------------
# FONT SIZES
# -----------------------------------------------------------------------------
splash_font_size = 48.0
placeholder_font_size = 48.0
demo_watermark_font_size = 24.0

# -----------------------------------------------------------------------------
# INPUT FIELD SETTINGS
# -----------------------------------------------------------------------------
input_label = "3-digit hip number:"
input_max_length = 3
input_field_width = 45.0

# -----------------------------------------------------------------------------
# NAVIGATION SETTINGS
# -----------------------------------------------------------------------------
enable_arrow_nav = true

# -----------------------------------------------------------------------------
# DEMO WATERMARK POSITIONING
# -----------------------------------------------------------------------------
demo_watermark_x_offset = 200.0
demo_watermark_y_offset = 10.0
demo_watermark_width = 180.0
demo_watermark_height = 30.0

# -----------------------------------------------------------------------------
# UI SPACING & STYLING
# -----------------------------------------------------------------------------
ui_spacing = 10.0
stroke_width = 1.0
invalid_input_timeout = 0.5
no_video_popup_timeout = 2.0

# -----------------------------------------------------------------------------
# TEXT LABELS
# -----------------------------------------------------------------------------
now_playing_label = "now playing"
company_label = "SUMMIT PROFESSIONAL Solutions"

# -----------------------------------------------------------------------------
# COLOR SETTINGS (Hex Format)
# -----------------------------------------------------------------------------
input_text_color = "#FFFFFF"
input_stroke_color = "#FFFFFF"
label_color = "#FFFFFF"
background_color = "#000000"

# =============================================================================
# END OF CONFIGURATION
# =============================================================================