# Cross-compilation configuration
# https://github.com/cross-rs/cross

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"

# Install all dependencies needed for compilation
pre-build = [
    "apt-get update",
    "apt-get install -y libavutil-dev libavcodec-dev libavformat-dev libswscale-dev libswresample-dev libavfilter-dev libavdevice-dev",
    "apt-get install -y libasound2-dev libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev",
    "apt-get install -y libwayland-dev libxkbcommon-dev pkg-config clang",
]

[target.x86_64-pc-windows-gnu]
image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu:main"

# Minimal Windows setup - FFmpeg DLLs will be bundled by xtask
pre-build = [
    "dpkg --add-architecture i386",
    "apt-get update",
]
