name: Unified Build (xtask)

on:
  push:
    branches: [main]

jobs:
   validate:
     name: Code Quality & Security
     runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Clippy
        run: cargo clippy --package xtask -- -D warnings

   build-linux:
     name: Build Linux
     runs-on: ubuntu-latest
     needs: validate
     container:
       image: ubuntu:24.04
     steps:
       - name: Install system dependencies
         run: |
           apt-get update
           apt-get install -y git curl build-essential pkg-config clang

       - uses: actions/checkout@v4

       - name: Install Rust
         uses: dtolnay/rust-toolchain@stable

       - name: Install FFmpeg and dependencies
         run: |
           apt-get update
           apt-get install -y \
             libasound2-dev \
             libavutil-dev libavcodec-dev libavformat-dev \
             libswscale-dev libswresample-dev libavfilter-dev \
             libavdevice-dev \
             pkg-config clang

       - name: Build with xtask
         run: |
           cargo build --package xtask --release
           ./target/release/xtask dist --platform linux --variant full