name: Build Distributions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build .
      - name: Create zip
        run: |
          cd result
          zip -r ../summit_hip_numbers-linux.zip .
      - run: cp summit_hip_numbers-linux.zip dist/
      - uses: actions/upload-artifact@v4
        with:
          name: linux-bundle
          path: summit_hip_numbers-linux.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-pc-windows-gnu
          targets: x86_64-unknown-linux-gnu
      - name: Install GStreamer
        run: |
          curl -o gst.msi https://gstreamer.freedesktop.org/data/pkg/windows/1.24.10/mingw/gstreamer-1.0-mingw-x86_64-1.24.10.msi
          msiexec /i gst.msi /quiet /norestart
       - run: cargo build --release --target x86_64-pc-windows-gnu
      - name: Create zip
        run: |
          mkdir bundle
          cp target/release/summit_hip_numbers.exe bundle/
          cp config.toml bundle/
          cp -r videos bundle/ 2>$null
          cp -r splash bundle/ 2>$null
          cp "C:/gstreamer/1.0/mingw_x86_64/bin/*.dll" bundle/
          mkdir bundle/plugins
          cp -r "C:/gstreamer/1.0/mingw_x86_64/lib/gstreamer-1.0" bundle/plugins/
          Compress-Archive -Path bundle -DestinationPath summit_hip_numbers-windows.zip
      - run: cp summit_hip_numbers-windows.zip dist/
      - uses: actions/upload-artifact@v4
        with:
          name: windows-bundle
          path: summit_hip_numbers-windows.zip

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: determinate-systems/nix-installer-action@main
      - run: nix build .#macos
      - name: Create zip
        run: |
          cd result
          zip -r ../summit_hip_numbers-macos.zip .
      - run: cp summit_hip_numbers-macos.zip dist/
      - uses: actions/upload-artifact@v4
        with:
          name: mac-bundle
          path: summit_hip_numbers-macos.zip

  release:
    needs: [build-linux, build-windows, build-mac]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux-bundle
      - uses: actions/download-artifact@v4
        with:
          name: windows-bundle
      - uses: actions/download-artifact@v4
        with:
          name: mac-bundle
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            summit_hip_numbers-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
