name: Unified Build (xtask)

on:
  push:
    branches: [main]

jobs:
  validate:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Clippy
        run: cargo clippy --package xtask -- -D warnings

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev \
            libssl-dev \
            libavutil-dev libavcodec-dev libavformat-dev \
            libswscale-dev libswresample-dev libavfilter-dev \
            libavdevice-dev \
            pkg-config clang

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build with xtask
        run: |
          cargo build --package xtask --release
          ./target/release/xtask dist --platform linux --variant full