name: Unified Build (xtask)

on:
  push:
    branches: [main]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # ============================================================================
  # VALIDATION - Code Quality & Security
  # ============================================================================

  validate:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      # Install system dependencies needed for compilation (Clippy needs to compile)
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev \
            libssl-dev \
            libavutil-dev libavcodec-dev libavformat-dev \
            libswscale-dev libswresample-dev libavfilter-dev \
            libavdevice-dev \
            pkg-config clang

      - name: Format Check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --package xtask -- -D warnings

      - name: Security Audit
        run: |
          cargo install cargo-audit
          cargo audit

  # ============================================================================
  # BUILD ALL PLATFORMS - Using xtask
  # ============================================================================

  build-all:
    name: Build All Platforms
    runs-on: ${{ matrix.os }}
    needs: validate
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds - native on Ubuntu
           - os: ubuntu-latest
             platform: linux
             variant: full

           - os: ubuntu-latest
             platform: linux
             variant: demo

           # macOS builds - must run on macOS
           - os: macos-latest
             platform: macos
             variant: full

           - os: macos-latest
             platform: macos
             variant: demo

           # Windows builds - native on Windows
           - os: windows-latest
             platform: windows
             variant: full

           - os: windows-latest
             platform: windows
             variant: demo

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}-${{ matrix.platform }}-${{ matrix.variant }}

      # Linux-specific: Install system dependencies
      - name: Install Linux Dependencies
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev \
            libavutil-dev libavcodec-dev libavformat-dev \
            libswscale-dev libswresample-dev libavfilter-dev \
            libavdevice-dev \
            pkg-config clang

      # macOS-specific: Install FFmpeg via Homebrew
      - name: Install macOS Dependencies
        if: matrix.platform == 'macos'
        run: |
          brew install ffmpeg pkg-config
          # Set paths for FFmpeg headers (needed for bindgen)
          echo "CPATH=/opt/homebrew/include:$CPATH" >> $GITHUB_ENV
          echo "LIBRARY_PATH=/opt/homebrew/lib:$LIBRARY_PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      # Install Docker for cross-compilation (Linux from Ubuntu)
      - name: Set up Docker
        if: matrix.platform == 'linux'
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      # Install cross for Linux builds
      - name: Install Cross
        if: matrix.platform == 'linux'
        run: |
          cargo install cross --git https://github.com/cross-rs/cross

      # Build using xtask
      - name: Build with xtask
        run: |
          cargo build --package xtask --release
          ./target/release/xtask dist --platform ${{ matrix.platform }} --variant ${{ matrix.variant }}
        shell: bash

      # Upload artifacts
      - name: Upload Distribution
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.variant }}-dist
          path: |
            dist/*.zip
            dist/*.tar.gz
            dist/*.dmg
          retention-days: 30

  # ============================================================================
  # TEST DISTRIBUTIONS
  # ============================================================================

  test-dist:
    name: Test ${{ matrix.platform }} Distribution
    runs-on: ${{ matrix.os }}
    needs: build-all
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            os: ubuntu-latest
            variant: full

          - platform: macos
            os: macos-latest
            variant: full

          - platform: windows
            os: ubuntu-latest
            variant: full

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.variant }}-dist

      - name: Test Linux Distribution
        if: matrix.platform == 'linux'
        run: |
          echo "Testing Linux distribution..."
          tar -tzf *.tar.gz | head -20
          tar -xzf *.tar.gz

          # Find and test binary
          BINARY=$(find . -name "summit_hip_numbers" -type f -executable | head -n 1)
          if [ -z "$BINARY" ]; then
            echo "ERROR: Binary not found"
            exit 1
          fi

          echo "✓ Found binary: $BINARY"
          file "$BINARY"
          ldd "$BINARY" || echo "Note: ldd failed"

      - name: Test macOS Distribution
        if: matrix.platform == 'macos'
        run: |
          echo "Testing macOS distribution..."
          unzip -l *.zip | head -20
          unzip *.zip

          # Find app bundle
          APP=$(find . -name "*.app" -type d | head -n 1)
          if [ -z "$APP" ]; then
            echo "ERROR: App bundle not found"
            exit 1
          fi

          echo "✓ Found app bundle: $APP"
          ls -la "$APP/Contents/MacOS/"

      - name: Test Windows Distribution
        if: matrix.platform == 'windows'
        run: |
          echo "Testing Windows distribution..."
          unzip -l *.zip | head -20
          unzip *.zip

          # Find executable
          EXE=$(find . -name "*.exe" -type f | head -n 1)
          if [ -z "$EXE" ]; then
            echo "ERROR: Executable not found"
            exit 1
          fi

          echo "✓ Found executable: $EXE"
          file "$EXE"

  # ============================================================================
  # BUILD SUMMARY
  # ============================================================================

  summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [build-all, test-dist]
    if: always()
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate Summary
        run: |
          echo "# Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Artifacts" >> $GITHUB_STEP_SUMMARY
          find artifacts -type f \( -name "*.zip" -o -name "*.tar.gz" -o -name "*.dmg" \) -exec sh -c '
            for file; do
              size=$(du -h "$file" | cut -f1)
              echo "- $(basename "$file") ($size)" >> $GITHUB_STEP_SUMMARY
            done
          ' sh {} +

  # ============================================================================
  # RELEASE
  # ============================================================================

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-all, test-dist]
    if: github.event_name == 'release'
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare Release Files
        run: |
          mkdir -p release
          find artifacts -type f \( -name "*.zip" -o -name "*.tar.gz" -o -name "*.dmg" \) -exec cp {} release/ \;
          ls -lh release/

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          generate_release_notes: true
          fail_on_unmatched_files: true