name: Build Distributions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
   build-linux:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: cachix/install-nix-action@v25
         with:
           nix_path: nixpkgs=channel:nixos-unstable
       - run: nix build .
       - name: Create zip
         run: zip -r summit_hip_numbers-linux.zip result
       - run: cp summit_hip_numbers-linux.zip dist/
       - uses: actions/upload-artifact@v4
         with:
           name: linux-bundle
           path: summit_hip_numbers-linux.zip
 
   build-windows:
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v4
       - name: Setup Rust
         run: |
           rustup update
           rustup target add x86_64-pc-windows-gnu
       - name: Run library tests
         run: cargo test --lib
       - name: Install GStreamer
         shell: pwsh
         run: |
           $gstreamerUrl = "https://gstreamer.freedesktop.org/data/pkg/windows/1.26.6/mingw/gstreamer-1.0-mingw-x86_64-1.26.6.msi"
           $installerPath = "$env:TEMP\gstreamer-installer.msi"
           Write-Host "Downloading GStreamer MSI from $gstreamerUrl..."
           Invoke-WebRequest -Uri $gstreamerUrl -OutFile $installerPath
           Write-Host "Installing GStreamer..."
           Start-Process msiexec.exe -ArgumentList "/i $installerPath /quiet /norestart" -Wait
           Write-Host "GStreamer installation completed"
       - name: Run the Windows build script
         shell: pwsh
         run: .\build_windows.ps1
       - uses: actions/upload-artifact@v4
         with:
           name: windows-bundle
           path: summit_hip_numbers_portable.zip

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: ./install_macos.sh --skip-build
      - name: Run the macOS build script
        run: ./build_macos.sh
      - uses: actions/upload-artifact@v4
        with:
          name: mac-bundle
          path: dist/macos/*.dmg

  release:
    needs: [build-linux, build-windows, build-mac]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux-bundle
      - uses: actions/download-artifact@v4
        with:
          name: windows-bundle
      - uses: actions/download-artifact@v4
        with:
          name: mac-bundle
      - name: Extract bundles to dist
        run: |
          mkdir -p dist
          unzip summit_hip_numbers-linux.zip -d dist/linux/
          unzip summit_hip_numbers_portable.zip -d dist/windows/
           cp *.dmg dist/mac/
       - uses: softprops/action-gh-release@v2
         with:
           files: |
             summit_hip_numbers-*.zip
             *.dmg
           token: ${{ secrets.GITHUB_TOKEN }}
