name: Unified Build (xtask)

on:
  push:
    branches: [main]

jobs:
  validate:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Clippy
        run: cargo clippy --package xtask -- -D warnings

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build with xtask
        run: |
          cargo build --package xtask --release
          ./target/release/xtask dist --platform linux --variant full