name: Build Windows Distribution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  MSYS2_INSTALL_DIR: C:\msys64
  INNO_SETUP_VERSION: 6.2.2

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSYS2 and GStreamer dependencies
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-glib2
          mingw-w64-x86_64-gstreamer
          mingw-w64-x86_64-gst-plugins-base
          mingw-w64-x86_64-gst-plugins-good
          mingw-w64-x86_64-gst-plugins-bad
          mingw-w64-x86_64-gst-plugins-ugly
        update: true
        path-type: inherit

    - name: Set up Rust (GNU toolchain)
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable-x86_64-pc-windows-gnu

    - name: Build Application
      shell: msys2 {0}
      env:
        PKG_CONFIG_PATH: /mingw64/lib/pkgconfig
        RUSTFLAGS: -L native=/mingw64/lib
      run: cargo build --release --verbose

    - name: Download and Install Inno Setup
      shell: pwsh
      run: |
        $inno_url = "https://files.jrsoftware.org/is/6/innosetup-${{ env.INNO_SETUP_VERSION }}.exe"
        $inno_path = "${{ runner.temp }}\innosetup.exe"
        Write-Host "Downloading Inno Setup from $inno_url"
        Invoke-WebRequest -Uri $inno_url -OutFile $inno_path
        Write-Host "Installing Inno Setup..."
        Start-Process -FilePath $inno_path -ArgumentList "/SP- /VERYSILENT /SUPPRESSMSGBOXES /NOCANCEL /NORESTART" -Wait
        $inno_dir = "C:\Program Files (x86)\Inno Setup 6"
        Write-Host "Adding '$inno_dir' to GITHUB_PATH"
        echo $inno_dir >> $env:GITHUB_PATH

    - name: Run Build Script to Create Distribution
      shell: pwsh
      run: |
        Write-Host "=== Running Build Script to Create Distribution ===" -ForegroundColor Cyan
        ./build_windows.ps1 -SkipBuild

    - name: Upload Portable Application as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: summit-hip-numbers-windows-portable
        path: summit_hip_numbers_portable.zip
        
    - name: Upload Installer as Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: summit-hip-numbers-windows-installer
        path: dist/summit_hip_numbers_installer.exe

  test-portable:
    runs-on: windows-latest
    needs: build-windows

    steps:
    - name: Download Portable Bundle
      uses: actions/download-artifact@v4
      with:
        name: summit-hip-numbers-windows-portable

    - name: Test Portable Executable
      shell: pwsh
      run: |
        Write-Host "=== Testing Portable Executable in Clean Environment ===" -ForegroundColor Cyan
        
        # Unzip the portable bundle
        if (Test-Path "summit_hip_numbers_portable.zip") {
          Expand-Archive -Path "summit_hip_numbers_portable.zip" -DestinationPath "test_portable" -Force
          Write-Host "Extracted portable bundle" -ForegroundColor Green
        } else {
          Write-Error "Portable zip not found!"
          exit 1
        }
        
        # Show contents
        Write-Host "`nPortable bundle contents:" -ForegroundColor Yellow
        Get-ChildItem -Path "test_portable" -Recurse | Select-Object FullName, Length | Format-Table
        
        # Check for executable
        $exePath = "test_portable\summit_hip_numbers.exe"
        if (-not (Test-Path $exePath)) {
          Write-Error "Executable not found at $exePath"
          exit 1
        }
        Write-Host "`nExecutable found: $exePath" -ForegroundColor Green
        
        # Check for critical DLLs
        Write-Host "`nChecking for critical DLLs:" -ForegroundColor Yellow
        $criticalDlls = @(
          "libglib-2.0-0.dll",
          "libgobject-2.0-0.dll", 
          "libgio-2.0-0.dll",
          "libgstapp-1.0-0.dll",
          "libgstreamer-1.0-0.dll"
        )
        
        $missingDlls = @()
        foreach ($dll in $criticalDlls) {
          $dllPath = "test_portable\$dll"
          if (Test-Path $dllPath) {
            Write-Host "  ✓ $dll" -ForegroundColor Green
          } else {
            Write-Host "  ✗ $dll MISSING" -ForegroundColor Red
            $missingDlls += $dll
          }
        }
        
        if ($missingDlls.Count -gt 0) {
          Write-Error "Missing critical DLLs: $($missingDlls -join ', ')"
          Write-Host "`nSearching for DLLs in test_portable:" -ForegroundColor Yellow
          Get-ChildItem -Path "test_portable" -Filter "*.dll" | ForEach-Object {
            Write-Host "  Found: $($_.Name)"
          }
          exit 1
        }
        
        # Try to run the executable briefly
        Write-Host "`nAttempting to run executable for 10 seconds..." -ForegroundColor Yellow
        $logFile = "test_portable\test-run.log"
        
        try {
          $process = Start-Process -FilePath $exePath -PassThru -NoNewWindow -RedirectStandardOutput $logFile -RedirectStandardError $logFile -WorkingDirectory "test_portable"
          Write-Host "Process started with PID: $($process.Id)" -ForegroundColor Green
          
          Start-Sleep -Seconds 10
          
          if (Get-Process -Id $process.Id -ErrorAction SilentlyContinue) {
            Write-Host "✓ Process is running successfully!" -ForegroundColor Green
            Stop-Process -Id $process.Id -Force
            Write-Host "Process stopped" -ForegroundColor Green
          } else {
            Write-Warning "Process exited early - check logs"
          }
        } catch {
          Write-Error "Failed to start process: $_"
          exit 1
        }
        
        # Show log output
        if (Test-Path $logFile) {
          Write-Host "`n=== Execution Log ===" -ForegroundColor Cyan
          Get-Content $logFile
          Write-Host "===================" -ForegroundColor Cyan
        }
        
        Write-Host "`n✓ Portable executable test completed successfully!" -ForegroundColor Green

    - name: Upload Test Log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: portable-test-log
        path: test_portable/test-run.log
        if-no-files-found: ignore